// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIMcUsA3RFG10Us8RenahElABsnb5gV4o',
    appId: '1:1009103376936:web:b862578ec7a8c09c0fdb1d',
    messagingSenderId: '1009103376936',
    projectId: 'kurumoappdev',
    authDomain: 'kurumoappdev.firebaseapp.com',
    storageBucket: 'kurumoappdev.appspot.com',
    measurementId: 'G-V299SES5ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuI6htsjHwsudpEXXKWYDxko3HNcRJrCo',
    appId: '1:1009103376936:android:f942d42ca1fda03c0fdb1d',
    messagingSenderId: '1009103376936',
    projectId: 'kurumoappdev',
    storageBucket: 'kurumoappdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_f_KT6Ih1z0z7Bj9LeK_BFkskZz9nVw',
    appId: '1:1009103376936:ios:1a8e22336973e3710fdb1d',
    messagingSenderId: '1009103376936',
    projectId: 'kurumoappdev',
    storageBucket: 'kurumoappdev.appspot.com',
    iosClientId: '1009103376936-sodteppvkgcjqak39c3b99cpigmpooh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurumoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_f_KT6Ih1z0z7Bj9LeK_BFkskZz9nVw',
    appId: '1:1009103376936:ios:b9654654b4e9d2e20fdb1d',
    messagingSenderId: '1009103376936',
    projectId: 'kurumoappdev',
    storageBucket: 'kurumoappdev.appspot.com',
    iosClientId: '1009103376936-ae5ig157lpq866qa01m1cbivg4854vm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurumoApp.RunnerTests',
  );
}
